---
- name: Install Apache 
  hosts: all
  become: true
  tasks:
    - name: Update Repo
      apt:
       update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install apache
      apt:
        name: "{{item}}"
        state: present 
      with_items:
        - apache2
        - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    - name: Update Repo
      dnf:
       update_cache: yes
      when: ansible_distribution == "CentOS"
      
    - name: Install httpd
      dnf:
        name: "{{item}}"
        state: present 
      with_items:
        - httpd
        - php
      when: ansible_distribution == "CentOS"